---
- hosts: all
  become: true
  tasks:
    - name: Make sure we can connect
      ping:
    - name: Update the apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install PHP
      apt: 
        name:
          - php
          - php-fpm
          - php-mysql
          - php-xml
        state: present
    - name: Remove apache2
      apt: name=apache2 state=absent
    - name: Install MySQL
      apt:
        name:
          - mysql-server-8.0
          - python3-mysqldb
    - name: Generate new root password
      command: openssl rand -hex 7
      register: mysql_new_root_password  
    - name: Remove anonymous users
      mysql_user: name="" state=absent
    - name: Remove test database
      mysql_db: name=test state=absent
    - name: Update root password
      mysql_user: 
        name: root
        host:
          - "{{ansible_hostname}}"
          - 127.0.0.1
          - ::1
          - localhost
        password: "{{mysql_new_root_password.stdout}}"
    - name: Output new root password
      debug: msg="new root password is {{mysql_new_root_password.stdout}}"
