---
- hosts: all
  become: true
  tasks:
    - name: Make sure we can connect
      ping:

    - name: Update the apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install PHP
      apt: 
        name:
          - php
          - php-fpm
          - php-mysql
          - php-xml
          - unzip
        state: present

    - name: Remove apache2
      apt: name=apache2 state=absent

    - name: Install MySQL
      apt:
        name:
          - mysql-server-8.0
          - python3-mysqldb

    - name: Generate new root password
      command: openssl rand -hex 7 creates=/root/.my.cnf
      register: mysql_new_root_password

    - debug: msg="New root password is {{ mysql_new_root_password.stdout }}"
      when: mysql_new_root_password.changed

    - debug: msg="No change to root password"
      when: not mysql_new_root_password.changed

    - name: Remove anonymous users
      mysql_user: name="" state=absent
      when: mysql_new_root_password.changed

    - name: Remove test database
      mysql_db: name=test state=absent
      when: mysql_new_root_password.changed

    - name: Update root password
      mysql_user: 
        name: root
        host_all: true
        password: "{{mysql_new_root_password.stdout}}"
      when: mysql_new_root_password.changed

    - name: Output new root password
      debug: msg="new root password is {{mysql_new_root_password.stdout}}"

    - name: Create my.cnf
      template: src=templates/mysql/my.cnf dest=/root/.my.cnf
      when: mysql_new_root_password.changed

    - name: Install nginx
      apt: name=nginx state=present

    - name: Start nginx
      service: name=nginx state=started

    - name: Create nginx config
      template: src=templates/nginx/default dest=/etc/nginx/sites-available/default
      notify: restart nginx

    - name: Restart nginx
      service: name=nginx state=restarted
        
    - name: Get Wordpress checksum
      uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
      register: wp_checksum

    - name: Download Wordpress
      get_url: url=https://wordpress.org/latest.zip dest=/tmp/wordpress.zip checksum="sha1:{{wp_checksum.content}}"

    - name: Unzip wordpress
      unarchive: src=/tmp/wordpress.zip dest=/tmp copy=no creates=/tmp/wordpress/wp-settings.php

    - name: Install required tools for wordpress
      apt:
        name:
          - unzip
        state: present

    - name: Create project folder
      file: dest=/var/www/html/

    - name: Copy wordpress files
      command: cp -a /tmp/wordpress/. /var/www/book.example.com creates=/var/www/book.example.com/wp-settings.php

    - name: Create Wordpress MYSql database
      mysql_db: name=wordpress state=present

    - name: Create Wordpress MySQL user 
      mysql_user: name=wordpress host=localhost password=bananas priv=wordpress.*:ALL
    
    - name: Create wp-config
      template: src=templates/wordpress/wp-config.php dest=/var/www/book.example.com/wp-config.php

    - name: Does the database exist?
      command: mysql -u root wordpress -e "SELECT ID FROM wordpress.wp_users LIMIT 1;"
      register: db_exist
      ignore_errors: true 
      changed_when: false

    - name: Copy Wordpress DB 
      copy: src=files/wp-database.sql dest=/tmp/wp-database.sql
      when: db_exist.rc > 0

    - name: Import Wordpress DB 
      mysql_db: target=/tmp/wp-database.sql state=import name=wordpress 
      when: db_exist.rc > 0

  handlers: 
    - name: restart nginx
      service: name=nginx state=restarted


